# Generated by Django 5.0.1 on 2024-03-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='React',
        ),
    ]
