# Generated by Django 5.0.1 on 2024-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_rename_pizza_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
