# Generated by Django 5.0.1 on 2024-04-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('pizzas', models.ManyToManyField(to='pizzas.react')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizzas.usuario')),
            ],
        ),
    ]
