# Generated by Django 5.0.1 on 2024-04-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_remove_usuario_telefone_alter_usuario_id_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='image',
        ),
    ]
