# Generated by Django 5.0.4 on 2024-04-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_remove_react_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('react', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.react')),
            ],
        ),
    ]
