# Generated by Django 5.0.4 on 2024-04-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0010_remove_tamanho_preco_pizzatemtamanho_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanho',
            name='react',
        ),
    ]
